//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab10_1.Parameters {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PathsAndURLs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PathsAndURLs() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab10_1.Parameters.PathsAndURLs", typeof(PathsAndURLs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на //div[@class = &quot;grid grid-rows-[auto_auto_1fr_auto] min-h-screen&quot;]/header/div[1]/div[1]/div[1]/nav[1]/div[2]/ul/li[2]/a.
        /// </summary>
        internal static string abLab {
            get {
                return ResourceManager.GetString("abLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://www.drweb.by/.
        /// </summary>
        internal static string homePage {
            get {
                return ResourceManager.GetString("homePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на //div[@class = &quot;grid grid-rows-[auto_auto_1fr_auto] min-h-screen&quot;]/header/div[1]/div[1]/div[@class = &quot;flex gap-4 lg:[.search-showed_&amp;]:hidden&quot;]/button[1].
        /// </summary>
        internal static string menuButton {
            get {
                return ResourceManager.GetString("menuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на //div[@class = &quot;CONTENT&quot;]/div[1]/div[1]/form/div/div/input.
        /// </summary>
        internal static string searchInput {
            get {
                return ResourceManager.GetString("searchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на //div[@class = &quot;HEAD clearfix&quot;]/div[2]/div[2]/div[5]/dl/dd/div/ul/li[1]/a.
        /// </summary>
        internal static string virusLabrary {
            get {
                return ResourceManager.GetString("virusLabrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на //div[@class = &quot;HEAD clearfix&quot;]/div[2]/div[2]/div[5]/dl/dt.
        /// </summary>
        internal static string virusLibraryList {
            get {
                return ResourceManager.GetString("virusLibraryList", resourceCulture);
            }
        }
    }
}
